#!/bin/bash
# Execute this from root directory.  You must have watchexec installed.
set -exuo pipefail


watchexec  \
   --project-origin . \
   --watch ../dialog-extensions/lib \
   --debounce=500ms \
   cp -Rf ../dialog-extensions/lib .
